# Generated by Django 5.0.2 on 2025-04-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('personal', 'Personal'), ('professional', 'Professional'), ('research', 'Research'), ('other', 'Other')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Developer', help_text='Your role in the project', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.CharField(default='Not specified', help_text='Tools and technologies used in the project', max_length=500),
        ),
    ]
