# Generated by Django 5.0.2 on 2025-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_project_type_project_role_project_team_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplate',
            name='template_file',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='template_path',
            field=models.CharField(default='resumes/professional_classic.html', max_length=255),
        ),
    ]
