# Generated by Django 5.0.2 on 2025-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_resumetemplate_template_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_branch',
            field=models.CharField(default='Any', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_course',
            field=models.CharField(default='Any', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='eligibility_year',
            field=models.CharField(default='Any', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='stipend_ctc',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full Time'), ('contract', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On-Site'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(related_name='jobs', to='users.skill'),
        ),
    ]
