# Generated by Django 5.0.2 on 2025-05-18 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_job_eligibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementofficer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='placementofficer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='placementofficer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='placementofficer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_officer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
