# Generated by Django 5.0.2 on 2025-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementofficer',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
