# Generated by Django 5.0.2 on 2025-05-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_placementofficer_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
