# Generated by Django 5.0.2 on 2025-05-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_communicationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/pdf/')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_academic_records', models.ManyToManyField(to='users.academicrecord')),
                ('selected_contests', models.ManyToManyField(to='users.contest')),
                ('selected_projects', models.ManyToManyField(to='users.project')),
                ('skills', models.ManyToManyField(to='users.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.studentprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resumetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CommunicationTemplate',
        ),
    ]
