# Generated by Django 5.0.2 on 2025-06-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studentresume_delete_communicationtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='selected_academic_records',
            field=models.ManyToManyField(related_name='resume_academic_records', to='users.academicrecord'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='selected_contests',
            field=models.ManyToManyField(related_name='resume_contests', to='users.contest'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='selected_projects',
            field=models.ManyToManyField(related_name='resume_projects', to='users.project'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='skills',
            field=models.ManyToManyField(related_name='resume_skills', to='users.skill'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.resumetemplate'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
