# Generated by Django 5.0.2 on 2025-07-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studentprofile_tenth_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='tenth_marks',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='twelfth_marks',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='10th Percentage'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='12th Percentage'),
        ),
    ]
