# Generated by Django 5.0.2 on 2025-07-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_studentprofile_tenth_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='resume_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/photos/'),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='users.studentprofile')),
            ],
        ),
    ]
